from pydantic import BaseModel, Field, Json
from datetime import datetime, time
from typing import Optional, Literal

class order(BaseModel):
    id: Optional[int] = None #Generated by Postgres
    user_id: int
    status: Literal['PLACED','CANCLED']
    total_amount: int
    currency: str
    metadata:Optional[Json]
    trace_id: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        from_attributes = True
        
class order_items(BaseModel):
    id: Optional[int]
    order_id: int
    sku: str
    name: str
    qty: int
    price: int # remove this
    