from pydantic import BaseModel, Field
from datetime import datetime, time
from typing import Optional

class order(BaseModel):
    id: Optional[int] = None #Generated by Postgres
    user_id: int
    status: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        from_attributes = True
    